theme = "tokyonight-non-italic"

[editor]
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = true
git-ignore = false

[editor.statusline]
left = ["mode", "separator", "file-name", "spinner"]
right = ["diagnostics", "selections", "file-type"]
separator = "∆"

mode.normal = "🌛 NORMAL"
mode.insert = "🌝 INSERT"
mode.select = "🌜 SELECT"

[keys.normal]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
"V" = ["select_mode", "extend_to_line_bounds"]
"g" = { "b" = "jump_backward" }

[keys.insert]
j = { k = "normal_mode" }

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
