[[language]]
name = "go"
config = { "build.expandWorkspaceToModule" = false }

[[language]]
name = "python"
roots = ["Pipfile"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
