import = [
    "~/.config/alacritty/themes/ayu_dark.toml"
]

[cursor.style]
shape = "Block"

[font]
size = 20

[font.bold]
family = "3270 Nerd Font Mono"
style = "Bold"

[font.italic]
family = "3270 Nerd Font Mono"
style = "Italic"

[font.normal]
family = "3270 Nerd Font Mono"
style = "Regular"

[window]
decorations = "Buttonless"

[window.padding]
x = 30
y = 15
